version: '3.8' # Use a recent version of the Compose file format
services:
  nextjs-app:
    container_name: real-time-wc-web-app
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the name of the Dockerfile
    ports:
      - '3000:3000' # Map port 3000 on the host to port 3000 in the container
    environment:
      - MONGODB_URI=mongodb://real-time-wc-mongodb:27017/realtimewebcomms
    volumes:
      - .:/usr/src/app # Mount the project directory in the container for live code changes
      - /usr/src/app/node_modules # Preserve node_modules that were installed inside the container
      - /usr/src/app/.next # Preserve the .next directory that gets created during the build process
    depends_on:
      - mongodb
    networks:
      - node-network # container bridge

  mongodb:
    container_name: real-time-wc-mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
# ref https://dev.to/scaabel/containerizing-a-nextjs-application-for-development-204d
# ref https://geshan.com.np/blog/2023/03/mongodb-docker-compose/
